/**
 * Records whether optional static assets exist, so components can hide
 * dead links at build time (e.g. the resume PDF download button — see
 * public/README.md). Runs on predev/prebuild; the output is committed.
 */
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const hasResumePdf = existsSync(`${root}public/resume.pdf`);

writeFileSync(
  `${root}data/generated/assets.ts`,
  `// Generated by scripts/check-assets.mjs — do not edit by hand.\nexport const hasResumePdf = ${hasResumePdf};\n`,
);
console.log(`check-assets: hasResumePdf=${hasResumePdf}`);
